### ISSUE TITLE
Get Cognito working w/ Hass

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/iac#16]
Should be able to use Cognito to log in to Ocean Builders Hass installations. (SSO for Pods).
Acceptance Criteria
Setup the apache mod proxy 
So that user could come from duckdns address and redirect to Home Assistant nana spot UI
Todo:
1. get the apache mod proxy working to bring that home a page 
2. Setup another app client for home assistant to work with cognito ; same user pool.
configure this on the rpi instance. [Os: Rpi os] 
there should be an addon or default option on HA config
3. Users put credentials in apache -->  should be bring up the ha from page without putting credentials again

[The end goal is to replace nabu casa]

**Comment by angiedear** [comment]
Blocked on Angie renewal issue.

**Comment by godslave05** [comment]
I was able to open the Home Assistant Login page from remote without nabu casa.  We are close to our end goal.
You can try it out
https://ha0507.duckdns.org/

**Comment by angiedear** [comment]
@scottdear @godslave05 can we close this issue?

**Comment by angiedear** [comment]
@godslave05 can we close this issue?

**Comment by angiedear** [comment]
@scottdear @godslave05 can we close this issue?

**Comment by angiedear** [comment]
@godslave05 can we close this issue?
