### ISSUE TITLE
Install IPFW ssh throttling

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/iac#3]
Install the firewall software on the AWS dev instance so that it disallows connections for that user and source IP for 5 minutes upon 10 unsuccessful attempts within 1 minute(or longer if is best practice).

Acceptance Criteria
-------------------------
After 10 unsuccessful ssh  login attempts port 22 is locked for 5 minutes
*IMPORTANT* ssh must unblock, if it does not the instance will be inaccessible and have to be mounted and unblocked.

**Comment by scottdear** [comment]
https://www.cyberciti.biz/faq/howto-limiting-ssh-connections-with-ufw-on-ubuntu-debian/

Above is a good article.  There's also ssh guard, and ipfw, either way, we need to rate limit requests.

Acceptance Criteria
-------------------------
After 10 unsuccessful ssh  login attempts port 22 is locked for 30 minutes
*IMPORTANT* ssh must unblock, if it does not the instance will be inaccessible and have to be mounted and unblocked.

**Comment by angiedear** [comment]
Medium t-shirt

**Comment by scottdear** [comment]
This needs to be an add-on and we need this installed on all exposed instances.

**Comment by scottdear** [comment]
AdGuard - Check this add-on to see if it has all the features we need.

**Comment by siddiqss** [comment]
Installed and configured Fail2Ban on Admin instance. Fail2Ban is an open-source tool which bans IP addresses for a certain period of time if there is any abuse of password authentication. It's better than SSH Guard in many ways.

**Comment by godslave05** [comment]
Need to write documentation. @siddiqss will provide it and keep it to seafile

**Comment by siddiqss** [comment]
Needs review. Asad will open a new link for the document

**Comment by diegopau** [comment]
We are not using a solution based on SSH anymore. Closing this.
