### ISSUE TITLE
Need to set up server in VPC along w/ SSL cert

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/iac#5]
Make a snapshot of server ola is working on
Create VPC
provision bastion host
write doc for how to access instnace via bastion host

**Comment by scottdear** [comment]
Large T-Shirt Size

**Comment by angiedear** [comment]
@scottdear is this still relevant?

**Comment by angiedear** [comment]
@scottdear is this issue still relevant?

**Comment by diegopau** [comment]
Not needed anymore, since we will be using a different remote connection method.
