### ISSUE TITLE
Cleanup Repositories

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/iac#8]
Delete Old repositories and open issues for repositories that need README files or updates to README files.

Acceptance Criteria
---------------------
1. All repositories remaining have code and/or README files
2. Any repositories w/out README files have new issues opened in the App Project to create/update the README.

**Comment by scottdear** [comment]
@diegopau I don't think I have permissions to delete any repositories, and there are some empty ones we want to delete, if that's OK.

**Comment by olagalal** [comment]
in progress

**Comment by omerll** [comment]
Stills in progress.
Please answer Angie, to help to close the issues =)

**Comment by angiedear** [comment]
In progress

**Comment by angiedear** [comment]
Blocked on responses about issues

**Comment by angiedear** [comment]
In Progress

**Comment by omerll** [comment]
Still in progress, conectivity issues...... PLEASE RESPOND TO ANGIE

**Comment by godslave05** [comment]
In progress

**Comment by siddiqss** [comment]
In progress

**Comment by omerll** [comment]
Omer has answered all the questions that angie posted on the issues!

**Comment by omerll** [comment]
Still in progress, PLEASE RESPOND TO ANGIE, HELP TO CLOSE THIS ISSUE @olagalal @godslave05

**Comment by diegopau** [comment]
Done
